src/components/DatePicker/DatePicker.vue

Removendo está alteração pois no teste no front-mfe-cadastros, o mesmo ficou desalinhado e fixado no topo do input.

fix: remove fixed calendar in top

---

src/components/ModalPromptUser/ModalPromptUser.vue
src/components/Stepper/StepperHeader/IStep.ts
src/components/Stepper/StepperHeader/StepperHeader.scss
src/components/Stepper/StepperHeader/StepperHeader.stories.js
src/components/Stepper/StepperHeader/StepperHeader.vue
src/components/Stepper/StepperHeader/__tests__/StepperHeader.spec.js
src/components/Stepper/StepperHeader/index.ts
src/components/Stepper/index.ts
src/examples/Stepper/StepperHeader.stories.js
src/main.ts

@Dirceu-Souza-Rezende @everton-ribeiro conforme combinamos antes, vamos no projeto de componente deixar de usar o Vuetify nos novos componentes que precisaremos criar.
No Design System aparecerá um componente de stepper. Ainda estão prototipando e acertando design. Ele será usado no futuro próximo no workflow da solicitação de limite (squad de crédito) mas vamos ver se usarão em outros lugares - quem sabe nos formulários @everton-ribeiro .
Com isso, montei a estrutura básica dele pra depois trabalharmos, quando entrar na sprint, e ter o esqueleto. Além disso, aproveitei pra testar o processo de não usar Vuetify (pra usar ícone, por exemplo, é só usar a tag i com a classe mdi, padrão do fontawesome).
Pra acessar a API, tem storybook já: …

feat: init structure for stepper header

---

src/components/DialogFooter/DialogFooter.scss
src/components/DialogFooter/DialogFooter.vue
src/components/DialogFooter/IExtraButton.ts
src/configurations/_functions.scss
src/configurations/_mixins.scss
src/configurations/_variables.scss

Refix o DialogFooter retirando qualquer referência ao vuetify. Aproveitei pra criar um mixin que recebe regras css para o breakpoint sm (até 600px) e uma função que retorna abstrai como setar o gutter/padding.

refactor: dialog footer

---

src/components/Stepper/StepperHeader/StepperHeader.scss
src/components/Stepper/StepperHeader/StepperHeader.vue
src/components/Stepper/StepperHeader/__tests__/StepperHeader.spec.js
src/components/Stepper/StepperHeader/_mixins.scss

@Dirceu-Souza-Rezende esse PR corrige o erro de quando a etapa sai de uma cor (exemplo: azul) e vai pro cinza, a linha estar sempre cinza.

fix: color blue/red to gray

---

src/components/ContextMenu/ContextMenu.scss
src/components/ContextMenu/ContextMenu.stories.js
src/components/ContextMenu/ContextMenu.vue
src/components/ContextMenu/__tests__/ContextMenu.spec.js
src/components/ContextMenu/index.ts
src/components/TableContextMenu/TableContextMenu.scss
src/components/TableContextMenu/TableContextMenu.stories.js
src/components/TableContextMenu/TableContextMenu.vue
src/main.ts

Essa implementação tem a criação de um componente análogo ao v-menu, chamado farm-contextmenu
juntamente com a aplicação dele no TableContextMenu.
No .scss do ContextMenu tive que deixar fixa a fonte, pq o bootstrap do Vuetify é quem coloca o font-family.
Por isso também no TableContextMenu tem o bootstrap do Vuetify, pra poder vir os estilos do v-list.
A STOR-148 vai tratar de tirar o v-list, então isso vai morrer depois.

feat: STOR-120 & refactor STOR-108

---

src/components/Icon/Icon.scss
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue
src/components/IconBox/IconBox.scss
src/components/IconBox/IconBox.stories.js
src/components/IconBox/IconBox.vue
src/components/IconBox/__tests__/IconBox.spec.js
src/components/IdCaption/IdCaption.vue

Ícones seguindo a nova paleta
Assim como o IconBox

feat: STOR-134 & STOR-135 colors icons

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.stories.js
src/components/Tooltip/Tooltip.vue

Esse PR corrige o problema do popup do tooltip desaparecer por conta do container pai e como o CSS trabalha com o posicionamento de elementos relatives.
Para contornar, tem que jogar o popup para ser um DOM Node do body.

fix: tooltip

---

src/components/layout/Col/Col.scss
src/components/layout/Col/Col.stories.js
src/components/layout/Col/Col.vue

Adicionada a prop cols para manter a compatibilidade com a API do vuetify: é a quantidade de colunas padrão, para quando não se define as de cada breakpoint.
Com isso será possível fazer um "replace all" em tudo, mas a indicação é irmos migrando aos poucos as telas.

feat: default cols prop (same vuetify API) STOR-189

---

src/components/CopyToClipboard/CopyToClipboard.stories.js
src/components/CopyToClipboard/CopyToClipboard.vue

Fix default success message
and add prop do customize it:

fix: copy to clipboard default success message

---

src/scss/FormOverrides.scss

A alteração do scss para ajustar o ícone no farm-textfield tinha quebrado os v-text-area, agora com essa alteração conserta o v-text-area e o ícone
Before
After:

fix: FormOverrides.scss

---

src/components/ResourceMetaInfo/ResourceMetaInfo.vue

- no need to import farm components (they are already bootstrapped)
- props doscs

refactor: resource metainfo imports

---

src/components/TextField/TextField.scss
src/components/TextField/TextField.stories.js

- scss using farm palette
- adjust layout using DS definition
- disabled documentation
- error state fix (do not show icon)

feat: better css and example for deprecated textfield STOR-76-77-187

---

src/components/Checkbox/Checkbox.vue
src/components/Checkbox/__tests__/Checkbox.spec.js
src/components/Form/Form.stories.js
src/components/Form/Form.vue
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/TextFieldV2/TextFieldV2.vue
src/components/TextFieldV2/__tests__/TextFieldV2.spec.js

When form validation restarts
the form fields return to a pristine state
The previous behavior to reset is the same, fields are still marked as touched and if they are invalid, proper UI and messages are shown

feat: make form fields pristine when form validation restarts

---

src/components/ContextMenu/ContextMenu.vue

When context menu is closed, the calculated top and left position were not being reseted. In some scenarios it added an extra scroll to the page due to it absolute positioning:

fix: contextmenu position set to 0 when closes

---

src/components/Modal/Modal.vue
src/components/RadioGroup/RadioGroup.stories.js

When component is mounted, it must be bootstrapped (calculate zindex and add event listeners).

fix: modal bootstrap

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.stories.js

Use rgba from SASS to add opacity in tooltip's background color.

fix: STOR-346

---

src/components/IdCaption/IdCaption.scss
src/components/IdCaption/IdCaption.stories.js
src/components/IdCaption/IdCaption.vue

Text ellipsis to IdCaption titles:
To achieve this UI, the component has been refactored; the action buttons/icons does not have absolute position and the component itself and the farm-typography elements must have max-width.

feat: STOR-348

---

src/components/Chip/Chip.stories.js
src/components/Chip/Chip.vue
src/components/DialogHeader/DialogHeader.scss
src/components/IdCaption/IdCaption.scss
src/components/Typography/Typography.scss
src/configurations/_mixins.scss

Added css ellipsis to farm-chip, so the chip will never break line if the chip is wider than the parent.

fix: STOR-356

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/TextArea/TextArea.vue
src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue
src/helpers/randomId.ts
tests/unit/helpers/randomId.spec.js

In select, textfield and textarea, the id have been defined as a prop and added to form native elements. The parent element has now a custom id, generated on the fly.
With this, when label (or farm-label) has the for attribute set and it matches with the id given for a certain farm form component, it receives focus.

feat: STOR-305

---

src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue

- A prop was included in the farm-textfield-v2 component that makes the text typed in the component appear in uppercase;

feat: add prop uppercase input-v2

---

src/components/Label/Label.scss
src/components/Label/Label.vue
src/components/SelectModalOptions/SelectModalOptions.stories.js

Fix colors in component
to avoid errors like this:
where the parent component has a different font color and the farm-label inherits it.

feat: label fix color from palette STOR-432

---

src/components/DataTableHeader/DataTableHeader.scss
src/components/DataTableHeader/DataTableHeader.stories.js
src/components/DataTableHeader/DataTableHeader.vue

In DataTableHeader, when user clicks on a cell that is not active to sort the previous behaviour was that it toggled the last value. Now, it does not toggle, so the user will the icon in its inactive state (example: ASC) and when the cell is clicked the icon goes to the active state (darker color) but does not toggle.
The previous behaviour could confuse the user.
Also it has been added a css transition when the icon is toggled.
https://user-images.githubusercontent.com/84783765/222114612-2daab7e1-8217-49ec-bfa0-4e463cdc236e.mov

feat: STOR-447

---

src/components/Label/Label.scss
src/components/Label/Label.stories.js
src/components/Tooltip/Tooltip.vue

Adjust typography (color, weight, etc...) from label and also add support in css to keep the * indicator beside the text and before the tooltip:

refactor: STOR-483

---

src/components/Typography/Typography.scss
src/components/Typography/Typography.stories.js
src/components/Typography/Typography.vue
src/configurations/_variables.scss

Enable black and its gradient colors to be used in typography:
by props.
Example:
`<farm-typography color="black" />`
`<farm-typography color="black" variation="80" />`

feat: STOR-507

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.vue

CSS adjusts in tooltip and change de default color to gray (#858585).

refactor: STOR-497

---

src/components/ContextMenu/ContextMenu.stories.js
src/components/ContextMenu/ContextMenu.vue
src/components/Select/Select.stories.js
src/helpers/index.ts
src/helpers/isChildOfFixedElement.js

When the context menu (or the Select, that uses it) is child of a fixed element, the context menu has an absolute position causing this following scenario:
https://user-images.githubusercontent.com/84783765/225690824-38e952ea-ae5e-4810-bc26-cff8f264efc1.mov
This PRs fixes it, checking whether the component is in the DOM bound to any element with position: fixed, traversing the DOM tree up and adding a fixed position to the context menu.
https://user-images.githubusercontent.com/84783765/225693158-01fc46cf-a3a7-4af3-b2a3-f6b01321ed3f.mov

fix: context menu fixed parent

---

src/components/ContextMenu/ContextMenu.stories.js
src/components/ContextMenu/ContextMenu.vue

Remove display: none and position the element outside the viewport, so the calculated dimensions won't be 0 and the previous positioning math keeps working.

fix: STOR-530

---

src/components/DataTableHeader/DataTableHeader.scss
src/components/DataTableHeader/DataTableHeader.vue

Added a lighter color to the sortable column icon that is nor sortable and when it becomes the sortable one, the color gets darker, with a smooth transition.
https://user-images.githubusercontent.com/84783765/226291350-06753ee6-2e45-4915-a920-2f968ce25aca.mov
Also a title attribute has been added to the ths elements that are sortable so the user will get a hint about the sorting behaviour:

feat: STOR-529

---

src/components/CopyToClipboard/CopyToClipboard.stories.js
src/components/CopyToClipboard/CopyToClipboard.vue
src/components/IdCaption/IdCaption.stories.js
src/components/IdCaption/IdCaption.vue

The copy to clipboard button in ID Caption color is primary:
but the tooltip color is golden:
Now the default color is also the primary:
And the ID Caption and the CopyToClipboard now have props to set buttons' colors.

feat: STOR-531

---

src/components/Label/Label.scss
src/components/Label/Label.stories.js
src/components/Switcher/Switcher.vue

- Fixed a bug in the farm-label component, when adding the tool type the * appeared even when a required prop was false;

fix: label with * even with false prop 

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue

Reflect Vuetify `allowed dates` property for datepicker: https://v2.vuetifyjs.com/en/components/date-pickers/#allowed-dates

feat: add ability to select only allowed dates in datepicker

---

package.json
src/components/Collapsible/Collapsible.stories.js
src/components/Collapsible/Collapsible.vue

Added a props to disable the export button on collapsible
this component had a withButton props which toggle the button render, if its false the export button won't show on layout.
now i added a new props which the button still shows but is disabled.
DOC: [Webpack App](https://storybook.plataforma.portalfarm.com.br/index.html?path=/docs/surfaces-collapsible--primary) 
PREVIEW:

refact: SCAD-2099

---

.gitignore
.prettierrc
.storybook/preview.js
package.json
src/components/Checkbox/Checkbox.stories.js
src/components/ContextMenu/ContextMenu.vue
src/components/DatePicker/DatePicker.scss
src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/customDatePicker.scss
src/components/TextFieldV2/TextFieldV2.vue
src/examples/Table.stories.js
src/helpers/date.ts

Esse PR contém uma nova implementação do farm-input-datepicker usando um componente standalone de datepicker:
https://vue3datepicker.com/
O componente do Vuetify 3 ainda está bem cru, faltando muitas funcionalidades. Para dar andamento ao processo de migração, adotei esse componente mantendo o mesmo comportamento, API do componente praticamente igual (ver o [migration guide](https://docs.google.com/document/d/1dMUzd1NmNX68-_1ltpbBMmeVnZ3h0kmN08oX1k9VxbA/edit), tive que fazer uma pequena mudança em uma prop chamada _allowed-dates_) e identidade visual bem semelhante.
https://github.com/Farm-Investimentos/front-mfe-components/assets/84783765/70dd1719-9099-4fcb-b4df-245868fa7617

feat: novo datepicker

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.vue

Make activator wrapper occupy whole part of farm-tooltip, so the tooltip corrrectly hides when mouse leaves it
[FRONT-578](https://dev-farm.atlassian.net/browse/FRONT-578)
[FRONT-578]: https://dev-farm.atlassian.net/browse/FRONT-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: FRONT-578

---

src/components/Logger/LoggerItem/LoggerItem.scss

This pull request includes a small change to the `LoggerItem.scss` file. The change adjusts the maximum width for the `LoggerItem` component when it is in horizontal mode.
* [`src/components/Logger/LoggerItem/LoggerItem.scss`](diffhunk://#diff-5c47b18640abbd09600dacbc8550677fe5497f5203b301d78539e510e6993850L72-R72): Changed the width from a fixed 158px to a max-width of 230px for better responsiveness.

Feat: SO-500

---

src/components/FilterEmptyState/FilterEmptyState.stories.js
src/components/FilterEmptyState/FilterEmptyState.vue
src/components/FilterEmptyState/__tests__/FilterEmptyState.test.js
src/components/FilterEmptyState/index.ts
src/shims-vue.d.ts

- Changed Vue component declaration to use DefineComponent for better type inference.
- Updated storybook configuration to include customizable title and subtitle props.
- Simplified template usage in stories by removing unnecessary props.
- Enhanced unit tests to cover new props and default behavior.
- Improved default prop values for better clarity and usability.

Fix: Erros nos testes e de FilterEmptyState
