package.json
src/components/Tabs/Tabs.vue

Chaged disabled color in Tabs component.

feat: change disabled color

---

package.json
src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/RangeDatePicker/__tests__/RangeDatePicker.spec.js

Ad min and max date to RangeDataPicker and its tests and storybook example.

feat: add min and max date to RangeDatePicker

---

package.json
src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/RangeDatePicker/__tests__/RangeDatePicker.spec.js

* feat: add min and max date to RangeDatePicker
* chore: update fix version
Co-authored-by: Chris Benseler - FARM <84783765+christian-benseler-farm@users.noreply.github.com>

feat: add min and max date to RangeDatePicker (#80)

---

src/components/TableContextMenu/TableContextMenu.vue
src/components/TableContextMenu/__tests__/TableContextMenu.spec.js

Fix table context menu and add tests

Fix table context menu pdig 565

---

package.json
src/components/MultipleSelectShortener/MultipleSelectShortener.stories.js
src/components/MultipleSelectShortener/MultipleSelectShortener.vue
src/components/MultipleSelectShortener/__tests__/MultipleSelectShortener.spec.js
src/components/MultipleSelectShortener/index.js
src/main.js

* feat: multiple select shortener component added
* chore: build
* chore: new minor version
* fix: .stories archive added
* Update MultipleSelectShortener.vue
* fix: lint

feat: multiple select shortener component added (#88)

---

package.json
src/components/MultipleSelectShortener/MultipleSelectShortener.vue

* feat: multiple select shortener component added
* chore: build
* chore: new minor version
* fix: .stories archive added
* fix: text size updated
* fix: changed to rem
* fix: font size in multiple select shortener
Co-authored-by: Christian Benseler FARM <christian.benseler@farminvestimentos.com.br>

fix: text size updated (#91)

---

src/components/TableContextMenu/TableContextMenu.scss
src/components/TableContextMenu/TableContextMenu.stories.js
src/components/TableContextMenu/TableContextMenu.vue

Add border bottom to TableContextMenu with multiple items.

Feature PDIG-788

---

src/examples/Table.stories.js

Add local pagination example to DataTableEmptyWrapper.

Add local pagination example PDIG-911

---

src/examples/Table.stories.js

* feat: add local pagination example
* feat: add DataTablePaginator

Add local pagination example PDIG-911 (#130)

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/RangeDatePicker/RangeDatePicker.vue

Remove default error icon from DatePicker

Remove default error icon from DatePicker PDIG-917

---

.storybook/vuetify_storybook.js
package.json
src/examples/ConfirmDialog.stories.js

Feat PDIG-967

---

src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.stories.js
src/components/Collapsible/Collapsible.vue
src/components/Collapsible/__tests__/Collapsible.spec.js
src/components/Collapsible/index.ts

Added Collapsible component from mfe-credito to mfe-components

Feature collapsible

---

src/main.ts

fix import and export in main.ts

fix: Collapsible component

---

package.json
src/components/Stepper/StepperHeader/StepperHeader.scss
src/components/Stepper/StepperHeader/StepperHeader.vue
src/examples/Modal.stories.js
src/scss/DefaultModal.scss

- Medium modal added
- Example Modal Extreme Small added
- Vertical StepHeader width updated

feat: Modal & Stepheader

---

package.json
src/examples/Buttons.stories.js
src/examples/Buttons.stories.scss
src/scss/ButtonOverrides.scss

* feat: button plain
* chore: upgrade version

feat: plain buttons (#205)

---

src/components/RadioButton/RadioButton.stories.js
src/components/RadioButton/RadioButton.vue

Fix multiple select and change props from labels to items

refactor: RadioButton selection

---

src/components/Buttons/ConfirmButton/ConfirmButton.stories.js
src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/Buttons/DefaultButton/DefaultButton.stories.js
src/components/Icon/Icon.scss
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue
src/components/Icon/__tests__/Icon.spec.js
src/components/Icon/index.ts
src/configurations/_variables.scss
src/examples/Icon.stories.js
src/examples/Icons.stories.scss
src/main.ts

New component for icons without vuetify dependency.

feat: farm-icon

---

src/examples/Form/Full.stories.js
src/examples/Form/Label.stories.js

* docs: example for full form
* fix: label

Docs form (#280)

---

src/components/IconBox/IconBox.scss
src/components/IconBox/IconBox.vue
src/components/IconBox/__tests__/IconBox.spec.js
src/configurations/sizes.ts
src/examples/Icon.stories.js
src/examples/IconBox.stories.js

Esse PR vai corrigir a dimensão do IconBox, deixando mais próximo do layout.

feat: STOR-25

---

src/components/AlertReload/AlertReload.scss
src/components/AlertReload/AlertReload.stories.js
src/components/AlertReload/AlertReload.vue
src/components/AlertReload/index.ts
src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/DialogFooter/DialogFooter.scss
src/components/Typography/Typography.scss
src/configurations/_mixins.scss
src/examples/AlertReload.stories.ts
src/main.ts

- removidas dependências do Vuetify
- melhoria na responsividade
- opção de exibir na vertical
- criação de mixins para auxiliar em media query
- criação de exemplos do AlertReload seguindo o novo padrão

feat: STOR-30

---

src/components/Typography/Heading/Heading.scss
src/components/Typography/Heading/Heading.stories.js
src/components/Typography/Heading/Heading.vue
src/components/Typography/Heading/__tests__/Heading.spec.js
src/components/Typography/Heading/configurations.ts
src/components/Typography/index.ts
src/examples/Typography/Heading.stories.js

Implementação do componente de typografia para heading, seguindo o Design System.

feat: STOR-35

---

src/components/Typography/Caption/Caption.scss
src/components/Typography/Caption/Caption.stories.js
src/components/Typography/Caption/Caption.vue
src/components/Typography/Caption/__tests__/Caption.spec.js
src/components/Typography/Caption/configurations.ts
src/components/Typography/index.ts
src/examples/Typography/Caption.stories.js

Criada a tipografia de Caption (farm-caption).

feat: STOR-43

---

package.json
src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/Checkbox.vue
src/components/Checkbox/__tests__/Checkbox.spec.js
src/components/Checkbox/index.ts
src/main.ts
tests/unit/index.js

feat: STOR-51

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/Checkbox.vue

Checkbox podendo estar disabled:

feat: STOR-63

---

src/components/layout/Container/Container.stories.js
src/components/layout/Row/Row.scss
src/components/layout/Row/Row.stories.js
src/components/layout/Row/Row.vue
src/components/layout/Row/__tests__/Row.spec.js
src/components/layout/Row/index.ts
src/main.ts

Esse PR é apenas com a base do farm-row (o atual v-row) que será usado depois juntamente com o farm-col (o atual v-col) e assim compondo o grid system.
As props dele (de alinhamento, gutter, etc) serão trabalhadas em outra task.

feat: STOR-93

---

src/components/Checkbox/Checkbox.vue
src/components/Checkbox/__tests__/Checkbox.spec.js
src/components/Form/Form.stories.js
src/components/Form/Form.vue
src/composition/__tests__/deepEqual.spec.js
src/composition/__tests__/validateFormFieldBuilder.spec.js
src/composition/__tests__/validateFormStateBuilder.spec.js
src/composition/deepEqual.ts
src/composition/validateFormFieldBuilder.ts
src/composition/validateFormMethodBuilder.ts
src/composition/validateFormStateBuilder.ts

O componente de Checkbox expõe uma API agora que pode ser usada pelo v-form e farm-form que habilita reset e validação.

feat: STOR-102 & 103

---

src/components/RadioGroup/RadioGroup.scss
src/components/RadioGroup/RadioGroup.stories.js
src/components/RadioGroup/RadioGroup.vue

feat: STOR-98

---

src/components/List/List.stories.js
src/components/List/List.vue
src/components/List/__tests__/List.spec.js
src/components/List/index.ts
src/components/ListItem/ListItem.scss
src/components/ListItem/ListItem.stories.js
src/main.ts

Novos componentes de lista e item de lista

feat: STOR-122

---

src/components/AlertReload/AlertReload.vue
src/components/ButtonToggle/ButtonToggle.vue
src/components/Buttons/ConfirmButton/ConfirmButton.vue
src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/Buttons/DefaultButton/DefaultButton.stories.js
src/components/Buttons/DefaultButton/DefaultButton.vue
src/components/Buttons/ExportButton/ExportButton.vue
src/components/Buttons/ImportButton/ImportButton.scss
src/components/Buttons/ImportButton/ImportButton.vue
src/components/Buttons/MultiImportButton/MultiImportButton.vue
src/components/Buttons/ToggleButton/ToggleButton.vue
src/components/CopyToClipboard/CopyToClipboard.vue
src/components/DatePicker/DatePicker.vue
src/components/DialogFooter/DialogFooter.vue
src/components/Logger/Logger.scss
src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.vue
src/components/Logger/LoggerItem/__tests__/LoggerItem.spec.js
src/components/MainFilter/MainFilter.vue
src/components/ModalPromptUser/ModalPromptUser.vue
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/TableContextMenu/TableContextMenu.scss
src/components/TableContextMenu/TableContextMenu.vue

feat: STOR-61

---

src/components/Typography/Typography.scss
src/components/Typography/Typography.stories.js
src/components/Typography/Typography.vue

feat: new palette colors in typography

---

src/components/Collapsible/Collapsible.vue
src/components/FilePicker/FilePicker.vue
src/components/Icon/Icon.scss
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue
src/components/IconBox/IconBox.scss
src/components/IconBox/IconBox.stories.js
src/components/IconBox/IconBox.vue
src/components/IconBox/__tests__/IconBox.spec.js
src/components/IdCaption/IdCaption.vue
src/components/TableContextMenu/TableContextMenu.scss
src/components/TableContextMenu/TableContextMenu.stories.js
src/components/TableContextMenu/TableContextMenu.vue

STOR-134 STOR-135 STOR-148 STOR-113 STOR-80

feat: multiple fixes from colors and lists

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/Checkbox.vue
src/components/DataTableHeader/DataTableHeader.scss
src/components/DataTableHeader/DataTableHeader.stories.js
src/components/DataTableHeader/DataTableHeader.vue

Alterado no componente custom de DataTableHeader o checkbox (retirado vuetify, usando farm-checkbox) e adicionadas variações de tamanho no farm-checkbox:

feat: STOR-66

---

src/components/ContextMenu/ContextMenu.vue
src/components/DataTableHeader/DataTableHeader.scss
src/components/TableContextMenu/TableContextMenu.stories.js

O ContextMenu nunca vai abrir pra fora da área da tela, sempre vai abrir 12 pixels antes no mínimo:

feat: STOR-149

---

src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue
src/components/TextFieldV2/__tests__/TextFieldV2.spec.js

Reset method added to TextFieldV2 and some validation examples

feat: STOR-233

---

src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue
src/components/TextFieldV2/__tests__/TextFieldV2.spec.js
src/components/Typography/Caption/Caption.vue

Hint text:
Hidden when there is an validation error:

feat: STOR-192 STOR-114

---

src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue

feat: STOR-235

---

package.json
src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue

Same API (usage) and output/behaviour

feat: v-mask support STOR-188

---

src/components/TextFieldV2/TextFieldV2.stories.js

Example toggle type & icon on icon press

docs: STOR-234

---

src/components/Label/Label.stories.js
src/components/Label/Label.vue

docs: STOR-193

---

src/components/Form/Form.stories.js

docs: example grid form

---

src/components/DialogFooter/DialogFooter.scss
src/components/layout/Line/Line.scss

- adjust space between buttons
- use farm css variable instead of vuetify' s

fix: STOR-251

---

src/components/CopyToClipboard/CopyToClipboard.stories.js
src/components/CopyToClipboard/CopyToClipboard.vue
src/components/IdCaption/IdCaption.stories.js
src/components/IdCaption/IdCaption.vue
src/components/layout/DisplayBreakpoints.stories.mdx

- prop in IdCaption to set a custom success message after copy to clipboard
- prop in IdCaption to set a custom color for the copy to clipboard tooltip

feat: STOR-253

---

src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.stories.js

New componente: farm-textfield-v2
Same API from farm-textfield (and Vuetify's Text Field) but no external dependency.

feat: STOR-179

---

src/components/ResourceMetaInfo/ResourceMetaInfo.scss
src/components/ResourceMetaInfo/ResourceMetaInfo.stories.js
src/components/ResourceMetaInfo/ResourceMetaInfo.vue
src/components/ResourceMetaInfo/__tests__/ResourceMetaInfo.spec.js
src/components/ResourceMetaInfo/index.ts
src/main.ts

feat: STOR-258

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/Form/Form.stories.js
src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/TextFieldV2/TextFieldV2.vue

- refactor input datepicker to use farm-textfield-v2
- refactor input range datepicker to use farm-textfield-v2
- form example with textfield-v2

refactor: textfield datepicker

---

src/components/Icon/Icon.scss
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue

Variação Lighten:
Variação Darken:

feat: STOR-212

---

src/components/Form/Form.stories.js
src/components/Select/Select.scss
src/components/Select/Select.stories.js
src/components/Select/Select.vue

feat: STOR-104 STOR-105

---

src/components/AlertBox/AlertBox.scss
src/components/AlertBox/AlertBox.stories.js
src/components/AlertBox/AlertBox.vue

Base:
With Icon:
Dismissible:
Dense:
Full:

feat: STOR-184

---

src/components/Select/Select.scss
src/components/Select/__tests__/Select.spec.js

fix: select v2 width STOR-284

---

src/components/DialogHeader/DialogHeader.vue

fix: STOR-257

---

src/components/IdCaption/IdCaption.vue

feat: change idcaption cta color

---

src/components/MainFilter/MainFilter.vue
src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.vue

fix: STOR-289

---

src/components/Form/Form.vue
src/components/Radio/Radio.scss
src/components/Radio/Radio.stories.js
src/components/Radio/Radio.vue
src/components/Radio/__tests__/Radio.spec.js
src/components/Radio/index.ts
src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/main.ts

New standalone Radio component (farm-radio)

feat: STOR-290

---

src/components/ValueCaption/ValueCaption.scss
src/components/ValueCaption/ValueCaption.stories.js
src/components/ValueCaption/ValueCaption.vue
src/components/ValueCaption/__tests__/ValueCaption.spec.js
src/components/ValueCaption/index.ts
src/main.ts

feat: STOR-302

---

src/components/Logos/ProductLogo/ProductLogo.stories.js

docs: STOR-59

---

src/components/DialogFooter/DialogFooter.vue
src/components/ModalPromptUser/ModalPromptUser.stories.js
src/components/ModalPromptUser/ModalPromptUser.vue

feat: STOR-304

---

src/components/Logger/Logger.scss
src/components/Logger/Logger.stories.js
src/components/Logger/Logger.vue
src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.stories.js
src/components/Logger/LoggerItem/LoggerItem.vue
src/components/Logger/__tests__/Logger.spec.js

Added info logger item color/status

feat: STOR-300

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/__tests__/DatePicker.spec.js
src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/RangeDatePicker/__tests__/RangeDatePicker.spec.js

- show datepicker when user clicks the calendar icon (in both single and range date pickers)
- created methods to handle datepicker visibility

feat: open datepicker from icon STOR-131

---

src/components/DataTablePaginator/DataTablePaginator.scss
src/components/DataTablePaginator/DataTablePaginator.stories.js
src/components/DataTablePaginator/DataTablePaginator.vue

refactor: STOR-307

---

src/components/MainFilter/MainFilter.stories.js
src/components/MainFilter/MainFilter.vue

- A parameter per slot was added in the main filter component where the label will be replaced by what will be passed in the slot.

feat: add slot components MainFilter

---

src/components/ValueCaption/ValueCaption.stories.js

docs: STOR-303

---

src/components/MainFilter/MainFilter.scss
src/components/MainFilter/MainFilter.stories.js
src/components/MainFilter/MainFilter.vue

feat: main filter input width

---

src/components/AlertBox/AlertBox.scss
src/components/AlertBox/AlertBox.stories.js
src/components/AlertBox/AlertBox.vue
src/components/AlertBox/__tests__/AlertBox.spec.js
src/components/Icon/Icon.scss

feat: STOR-71

---

src/components/Radio/Radio.scss
src/components/Radio/Radio.stories.js
src/components/Radio/Radio.vue

feat: STOR-296

---

src/components/MultipleFilePicker/MultipleFilePicker.stories.js
src/components/MultipleFilePicker/MultipleFilePicker.vue
src/components/MultipleFilePicker/__tests__/MultipleFilePicker.spec.js

- change button label
- show label only if user can add more files

fix: STOR-315

---

src/components/IconBox/IconBox.scss
src/components/IconBox/IconBox.vue

Adjust icon colors secondary and gray

fix: STOR-220

---

src/components/Radio/Radio.scss
src/components/Radio/Radio.stories.js
src/components/Radio/Radio.vue

Adicionado disabled e label e alguns outros ajustes:

feat: STOR-294

---

src/components/ContextMenu/ContextMenu.vue
src/components/Select/Select.scss
src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js

feat: STOR-310

---

src/components/ContextMenu/ContextMenu.scss

Add padding and remove border.
Figma:
Implementado:

feat: STOR-121

---

src/components/DialogHeader/DialogHeader.scss
src/components/DialogHeader/DialogHeader.stories.js

CSS ellipsis for long title in DialogHeader component

feat: STOR-347

---

src/components/ModalPromptUser/ModalPromptUser.stories.js
src/components/ModalPromptUser/ModalPromptUser.vue

Template slot for modal content

feat: STOR-350

---

src/components/TextArea/TextArea.scss
src/components/TextArea/TextArea.stories.js
src/components/TextArea/TextArea.vue
src/components/TextArea/__tests__/TextArea.spec.js
src/components/TextArea/index.ts
src/components/TextFieldV2/TextFieldV2.stories.js
src/main.ts

Created a new component for textarea: farm-textarea

feat: STOR-276

---

src/components/Buttons/DefaultButton/DefaultButton.scss

feat: STOR-374

---

src/components/DatePicker/DatePicker.vue
src/components/RangeDatePicker/RangeDatePicker.vue

RangeDatePicker using farm-contextmenu instead of v-menu

refactor: STOR-376

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue

Documentation for the events
Form/Select

docs: select events

---

src/components/AlertBox/AlertBox.vue
src/components/Typography/Typography.vue
src/configurations/typographyHtmlTags.ts

Allow alertbox content slot parent to have a different html tag.

feat: STOR-401

---

src/components/IdCaption/IdCaption.scss
src/components/IdCaption/IdCaption.stories.js
src/components/IdCaption/IdCaption.vue

- Added noSpacing prop to remove component height;

Add prop component id caption

---

.storybook/preview.js
package.json
src/examples/VuetifyDialog.stories.js
src/scss/VuejsDialog.scss

Documentation for the new dialog

docs: STOR-402

---

src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.stories.js
src/components/TextFieldV2/TextFieldV2.vue

Show hint text just in focus and  add persistentHint prop

feat: STOR-388

---

src/components/TextArea/TextArea.scss
src/components/TextArea/TextArea.stories.js
src/components/TextArea/TextArea.vue
src/components/TextFieldV2/TextFieldV2.scss
src/configurations/_mixins.scss

Add persistent hint prop and hint text just on focus in TextArea component.

feat: STOR-389

---

src/components/Select/Select.scss
src/components/Select/Select.stories.js
src/components/Select/Select.vue

Add persistent hint prop and hint text on focus.

feat: STOR-390

---

src/components/layout/Col/Col.scss
src/components/layout/Col/Col.stories.js
src/components/layout/Col/Col.vue

feat: offset STOR-412

---

src/components/layout/ContainerFooter/Container.stories.js
src/components/layout/ContainerFooter/ContainerFooter.scss
src/components/layout/ContainerFooter/ContainerFooter.vue

- Added a notop prop in the footer component that will remove the top margin of this component;

feat: add prop notop component ContainerFooter

---

src/components/Stepper/StepperHeader/StepperHeader.scss
src/components/Stepper/StepperHeader/StepperHeader.vue
src/components/Stepper/StepperHeader/_mixins.scss

Add color and bold to label from Stepper.
Before:
After:

feat: STOR-309

---

src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.vue

Adjust typography from LoggerItem.
Before:
After:

feat: STOR-219

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.stories.js
src/components/Checkbox/Checkbox.vue

adjust disabled colors, switch hexadecimals colors to variables and adjust sizes.
Before:
After:

feat: STOR-186

---

src/components/Select/Select.scss
src/components/Select/Select.vue
src/components/Select/__tests__/composition.spec.js
src/components/Select/composition/buildData.ts
src/components/Select/composition/index.ts

Do not allow user to type text in the select' s inner input element.

feat: STOR-416

---

src/components/Stepper/StepperHeader/StepperHeader.scss

feat: STOR-418

---

src/components/RangeDatePicker/RangeDatePicker.vue
src/scss/utils.scss

Adjust border from selected dates.

feat: STOR-419

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/__tests__/DatePicker.spec.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/RangeDatePicker/__tests__/RangeDatePicker.spec.js

Allow null value to DatePicker.

fix: STOR-425

---

src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/Buttons/DefaultButton/DefaultButton.stories.js
src/components/Buttons/DefaultButton/DefaultButton.vue

Add color variation to icon from button.

feat: STOR-213

---

src/scss/VuejsDialog.scss

Alter word-break from break-all to break-word.

fix: STOR-429

---

src/components/ListItem/ListItem.stories.js

docs: listitem hover

---

src/components/TabsV2/TabsV2.scss
src/components/TabsV2/TabsV2.stories.js
src/components/TabsV2/TabsV2.vue
src/components/TabsV2/__tests__/TabsV2.spec.js
src/components/TabsV2/index.ts
src/main.ts

Remove vuetify and add DS to Tabs.
Figma:
Impl:

feat: STOR-47/ STOR-181

---

src/components/layout/Line/Line.scss
src/components/layout/Line/Line.stories.js
src/components/layout/Line/Line.vue

Color prop for line (farm-line)

feat: STOR-454

---

src/components/DataTableEmptyWrapper/DataTableEmptyWrapper.scss
src/components/DataTableEmptyWrapper/DataTableEmptyWrapper.stories.js
src/components/DataTableEmptyWrapper/DataTableEmptyWrapper.vue
src/components/DataTableEmptyWrapper/__tests__/DataTableEmptyWrapper.spec.js

Prop to disable border in DataTableEmptyWrapper

feat: STOR-503

---

src/components/ModalPromptUser/ModalPromptUser.stories.js
src/components/ModalPromptUser/ModalPromptUser.vue

Example and documentation for event onConfirm

docs: STOR-428

---

src/configurations/_theme-colors-background.scss
src/configurations/_theme-colors-bw.scss
src/examples/Colors.stories.js
src/examples/Colors.stories.scss

Add new colors to pallete documentation:

docs: STOR-505

---

src/components/AlertBox/AlertBox.vue
src/components/Buttons/DefaultButton/DefaultButton.vue
src/components/Checkbox/Checkbox.vue
src/components/CopyToClipboard/CopyToClipboard.vue
src/components/Icon/Icon.vue
src/components/IconBox/IconBox.vue
src/components/IdCaption/IdCaption.vue
src/components/ListItem/ListItem.vue
src/components/ModalPromptUser/ModalPromptUser.vue
src/components/ProgressBar/ProgressBar.vue
src/components/Radio/Radio.vue
src/components/Tooltip/Tooltip.vue
src/components/Typography/Typography.vue
src/components/ValueCaption/ValueCaption.vue
src/components/layout/Line/Line.vue

Added new colors to PropType array:

docs: STOR-491

---

.storybook/preview-head.html
src/components/CardContext/__tests__/CardContext.spec.js
src/components/ContextMenu/ContextMenu.scss
src/components/DataTableEmptyWrapper/__tests__/DataTableEmptyWrapper.spec.js
src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.vue
src/scss/DialogOverrides.scss
src/scss/VuejsDialog.scss

- A new font was added in the storybook;
- The font style has been changed in some css;

refactor: 458

---

.storybook/preview.js
src/components/Chip/Chip.scss
src/components/Chip/Chip.stories.js
src/components/Chip/Chip.stories.scss
src/components/Chip/Chip.vue

Chips with new colors, typography and documentation

refactor: STOR-465

---

src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.vue
src/scss/utils.scss

Adjusts in tabs
Selected state
Hover
Full line

refactor: STOR-496

---

src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/Chip/Chip.vue
src/components/Typography/BodyText/BodyText.scss
src/components/Typography/Caption/Caption.scss
src/components/Typography/Caption/Caption.stories.js
src/components/Typography/Caption/Caption.vue
src/components/Typography/Caption/configurations.ts
src/components/Typography/Heading/Heading.scss
src/components/Typography/Heading/configurations.ts
src/components/Typography/Subtitle/Subtitle.scss

- Adjusted font size and weight in typography components;
- Added a new type option in the Caption component;

feat: STOR-459

---

src/components/Chip/Chip.vue
src/components/Typography/Small/Small.scss
src/components/Typography/Small/Small.stories.js
src/components/Typography/Small/Small.vue
src/components/Typography/Small/__tests__/Small.spec.js
src/components/Typography/Small/configurations.ts
src/components/Typography/index.ts

A new Small component has been created;

feat: STOR-460

---

src/components/DialogFooter/DialogFooter.scss
src/components/DialogFooter/DialogFooter.stories.js
src/components/DialogFooter/DialogFooter.vue

Adjusts in DialogHeader
Before:
After:

refactor: STOR-485

---

src/components/DialogHeader/DialogHeader.scss
src/components/Modal/Modal.scss
src/configurations/_mixins.scss

Adjusts in shadow, overlay bg color and border-radius.

refactor: STOR-488

---

.storybook/main.js
src/components/Buttons/DefaultButton/DefaultButton.scss
src/components/Buttons/DefaultButton/DefaultButton.stories.js

- Styling has been done on the button component;

feat: STOR-462

---

src/components/AlertBox/AlertBox.scss

Just changed the icon position (on start/top of component).

refactor: STOR-461

---

src/components/Switcher/Switcher.scss
src/components/Switcher/Switcher.stories.js
src/components/Switcher/Switcher.vue

CSS adjusts in Swticher + colors support.

refactor: STOR-495

---

src/components/Switcher/Switcher.vue
src/components/layout/Line/Line.scss
src/components/layout/Line/Line.stories.js
src/components/layout/Line/Line.vue

- Added the variation prop in the Line component;

feat: STOR-455

---

src/components/Card/Card.scss
src/components/Card/CardComposition.stories.ts
src/components/Card/CardContent/CardContent.scss
src/components/Card/CardContent/CardContent.stories.js
src/components/Card/CardContent/CardContent.vue
src/configurations/_theme-colors.scss

CSS adjustments and added a prop to farm-card-content to set a background from the defined colors in the DS for this purpose.

refactor: STOR-463

---

src/scss/VuejsDialog.scss

Adjusts in VueJSDialog to keep same UI from farm-dialog and its components.

refactor: STOR-489

---

src/components/Icon/Icon.scss
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue
src/components/ResourceMetaInfo/ResourceMetaInfo.vue
src/components/Switcher/Switcher.vue
src/components/Typography/Typography.stories.js
src/components/Typography/Typography.vue

**what was done**
- The inclusion of black colors was added to the Icon component;
- The value that is being repeated was removed from the types;
- Adjusted the colors of the ResourceMetaInfo component;

refactor: STOR-504

---

src/components/DataTableEmptyWrapper/DataTableEmptyWrapper.scss
src/components/DataTableEmptyWrapper/DataTableEmptyWrapper.vue

Use new typography and colors for component.

refactor: STOR-502

---

src/components/CopyToClipboard/CopyToClipboard.stories.js
src/components/CopyToClipboard/CopyToClipboard.vue
src/components/Icon/Icon.vue
src/components/IconBox/IconBox.stories.js
src/components/IconBox/IconBox.vue
src/components/IdCaption/IdCaption.vue
src/components/Typography/Typography.vue

- Adjusted the style of the IdCaption component;
- Added the sizeIcon prop in the Copytoclipboard component
- The prop variation was added in the IconBox component;
- Removed repeated types from Typography, IdCaption, IconBox, CopyToClipboard components;

feat: STOR-477

---

src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.stories.js
src/components/Collapsible/Collapsible.vue

- Adjusted the colors and font size in the collapsible component;
- Added a new feature containing the chip component;
- The documentation was updated;

refactor: STOR-468

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue

Allow set null ow empty array in select multiple.

fix: select multiple set null

---

src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.vue
src/components/Logger/LoggerItem/__tests__/LoggerItem.spec.js
src/components/Typography/Small/configurations.ts

- Adjusted font size and colors in the Logger component;

refqactor: STOR-493

---

src/components/Radio/Radio.scss
src/components/Radio/Radio.stories.js
src/components/Radio/Radio.vue

refactor: STOR-492

---

src/components/Stepper/StepperHeader/StepperHeader.scss

- The color variables of the Stepper component were adjusted

refactor: STOR-494

---

src/components/ListItem/ListItem.scss
src/components/TableContextMenu/TableContextMenu.scss
src/components/TableContextMenu/TableContextMenu.stories.js
src/components/TableContextMenu/TableContextMenu.vue

Adjusts in TableContextMenu
Hover

refactor: STOR-472

---

src/components/ListItem/ListItem.scss
src/components/Select/Select.scss
src/components/Select/Select.vue
src/components/TableContextMenu/TableContextMenu.scss
src/components/TextArea/TextArea.scss
src/components/TextArea/TextArea.vue
src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.vue

Refactor css for input, select and textarea components.

refactor: STOR-478 STOR-479 STOR-480

---

src/components/MultipleFilePicker/MultipleFilePicker.stories.js
src/components/MultipleFilePicker/MultipleFilePicker.vue
src/components/MultipleFilePicker/__tests__/MultipleFilePicker.spec.js

Reset method in MultipleFilePicker and story.

feat: STOR-288

---

src/components/DataTablePaginator/DataTablePaginator.scss

- Adjusted the font size and colors in the DataTablePaginator component;

refactor: STOR-490

---

src/components/DataTableHeader/DataTableHeader.scss
src/components/DataTableHeader/DataTableHeader.vue
src/components/Icon/Icon.vue

- Font size adjustment;
- Color adjustment in the header of the table;
- Change in sort icon;

refactor: STOR-470

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.vue

What was done:
- Adjusted the border and rounding of the checkboks;
- The repeated type of the prop has been removed

refactor: STOR-464

---

src/components/MultipleFilePicker/MultipleFilePicker.scss
src/components/MultipleFilePicker/MultipleFilePicker.vue

What was done:
- Adjusted font size colors;
- The component icon has been changed;
- The names of the variables referring to the colors were adjusted;

refactor: STOR-498

---

src/scss/Sticky-table.scss

- Adjusted font size colors;
- The names of the variables referring to the colors were adjusted;

refactor: STOR-469

---

src/components/Logger/Logger.scss
src/components/Logger/Logger.stories.js
src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.stories.js
src/components/Logger/LoggerItem/LoggerItem.vue
src/configurations/_variables.scss

Fixed the transition color from success to info. The scss that generates the class names have been refactored to build it dynamically from a list of colors/status.

fix: STOR-536

---

src/components/Switcher/Switcher.stories.js
src/components/Switcher/Switcher.vue

Story for outisde change v-model in Switcher component and refactor to Options API.

docs: STOR-7

---

src/components/Buttons/ExportButton/ExportButton.stories.js
src/components/Buttons/ExportButton/ExportButton.vue

feat: STOR-546

---

src/components/ResourceMetaInfo/ResourceMetaInfo.stories.js
src/components/ResourceMetaInfo/ResourceMetaInfo.vue
src/components/ResourceMetaInfo/__tests__/ResourceMetaInfo.spec.js

Added two new props to ResourceMetaInfo:
| Before | After |
| ------- |-------|
| ![image](https://user-images.githubusercontent.com/55860684/233174854-5274d16d-bcb5-4f60-bdbc-79af1e27a865.png) | ![image](https://user-images.githubusercontent.com/55860684/233174292-b3401c8b-666e-4f47-99fd-7b85e415c9d4.png) |

feat: STOR-549

---

src/components/Collapsible/Collapsible.vue
src/components/Icon/Icon.stories.js
src/components/Icon/Icon.vue
src/components/Icon/__tests__/Icon.spec.js

Refactor Icon component to use Vue 3 + Composition API

refactor: STOR-559

---

src/components/Checkbox/Checkbox.vue
src/components/Form/Form.vue
src/components/Radio/Radio.vue

Fix Radio button emit value and Form function that lists all the validatable components.

fix: STOR-561

---

src/components/Loader/Loader.stories.ts
src/components/Loader/Loader.vue

refactor: STOR-562

---

src/components/DatePicker/DatePicker.vue

**what was done**
- Fixed a bug when datepicker has min prop and field is not mandatory

Fix Datepicker 

---

src/components/ContextMenu/ContextMenu.vue
src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue

add ability to position context menu popup on top of activator

feat: add ability to position context menu popup on top of activator

---

src/components/RangeDatePicker/RangeDatePicker.vue

Add sort to dates from RangeDatePicker.

fix: FRONT-569

---

src/components/Logger/Logger.scss
src/components/Logger/Logger.stories.js
src/components/Logger/Logger.vue
src/components/Logger/LoggerItem/LoggerItem.scss
src/components/Logger/LoggerItem/LoggerItem.vue

Add two new possibilities in Logger component

feat: FRONT-571

---

src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue

**RANGEDATEPICKER**
added readonly props and user is now able to write a specific date.

feat: SCAD-2100

---

src/components/TextArea/TextArea.scss
src/components/TextFieldV2/TextFieldV2.scss

added new disabled background color to input, text, select and select autocomplete.

style: SCAD-2101

---

src/components/MainFilter/MainFilter.vue

added outlined button and icon to mainfilter button

refact: SCAD-2102

---

package.json
src/components/Modal/Modal.vue

Dev mode e build usando Node 18, suite de testes ok.
Adicionei no package.json uma chave com a definição da engine requerida.

feat: Vue3 + node18

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/__tests__/DatePicker.spec.js

Add new prop `multiple` for datepicker, which allows select multiple dates as `value`

feat: FRONT-572

---

src/components/DatePicker/DatePicker.stories.js
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/__tests__/DatePicker.spec.js
src/components/TextFieldV2/TextFieldV2.scss
src/components/TextFieldV2/TextFieldV2.vue
src/helpers/date.js

Show multiple chosen dates on input
Force datepicker input to be readonly when is multiple

feat: FRONT-573

---

src/components/DatePicker/DatePicker.scss
src/components/DatePicker/vDatePicker.scss

add padding for actions container in datepicker
Before:
After:

fix: FRONT-574

---

src/components/ListItem/ListItem.scss
src/components/Select/Select.scss
src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js

- Add option to pass disabled options to `select` component
- Add github link in Storybook

feat: FRONT-575

---

jest.config.js
src/components/Form/Form.stories.js
src/components/Form/Form.vue
src/components/Form/__tests__/Form.spec.js
src/components/Form/__tests__/helpers.js

When a form has dynamic fields, it needs to wait `nextTick` to get new fields to validate.

fix: form dynamic validation

---

src/components/DataTableHeader/DataTableHeader.scss
src/components/DataTableHeader/DataTableHeader.vue

always shows sort icon on table header
[FRONT-577](https://dev-farm.atlassian.net/browse/FRONT-577)
[FRONT-577]: https://dev-farm.atlassian.net/browse/FRONT-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: FRONT-577

---

src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js
src/components/SelectAutoComplete/SelectAutoComplete.vue
src/components/SelectAutoComplete/__tests__/SelectAutoComplete.spec.js

Add select All option to multiple select

Feat: SCR 1878

---

src/components/Buttons/ExportButton/ExportButton.stories.js
src/components/Buttons/ExportButton/ExportButton.vue

Add new props to ExportButton.

feat: 2160

---

src/components/Select/Select.stories.js
src/components/Select/Select.vue
src/components/Select/__tests__/Select.spec.js

Fix bug when selecting the checkbox would lead to incorrect behavior

Fix: SCR-1878

---

src/components/Buttons/DefaultButton/DefaultButton.vue

fix: button to prop

---

src/components/Icon/icons_list.ts

Add new icons:
assessment and rule

feat: add new icons: assessment, rule

---

src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue

This pull request adds new validation features to the `RangeDatePicker` component, allowing for more flexible date range validation and custom error messages. The most important changes include adding new stories for validation, updating the validation rules, and introducing new properties and methods to handle min/max date validation.
* [`src/components/RangeDatePicker/RangeDatePicker.stories.js`](diffhunk://#diff-4ef3962880289164edbab6c44e6fa576f04432ca7665aa031660536fe64c904cR96-R136): Added `ValidacaoInputPadrao` and `ValidacaoInputCustomizada` stories to demonstrate the new validation features.
* [`src/components/RangeDatePicker/RangeDatePicker.vue`](diffhunk://#diff-ae81c49f4f526e85e5486bb311055892110794cb01d36cea40cde42de7506156L51-R51): Modified the `rules` array to include the …

feat: SO-558

---

src/components/RangeDatePicker/RangeDatePicker.stories.js
src/components/RangeDatePicker/RangeDatePicker.vue
src/components/RangeDatePicker/__tests__/RangeDatePicker.spec.js

This pull request includes updates to the `RangeDatePicker` component and its associated tests and stories. The changes focus on updating date ranges, improving date validation logic, and adding comprehensive test coverage for date range validation.
* [`src/components/RangeDatePicker/RangeDatePicker.stories.js`](diffhunk://#diff-4ef3962880289164edbab6c44e6fa576f04432ca7665aa031660536fe64c904cL104-R109): Updated the date ranges in the `ValidacaoInputPadrao` and `ValidacaoInputCustomizada` stories from 2024 to 2025. [[1]](diffhunk://#diff-4ef3962880289164edbab6c44e6fa576f04432ca7665aa031660536fe64c904cL104-R109) [[2]](diffhunk://#diff-4ef3962880289164edbab6c44e6fa576f04432ca7665aa031660536fe64c904cL124-R132)
* [`src/components/RangeDatePicker/RangeDatePicker.vue`](diffhunk://#diff-ae81c49f4f …

fix: Improve RangeDatePicker date range validation logic

---

src/components/Icon/Icon.vue

Add custom icons listing

---

src/components/FilterEmptyState/index.ts

- Added detailed type definitions for FilterEmptyStateProps to improve clarity and usability.
- Included optional properties for empty and not found states, along with customizable image and text attributes.
- Ensured better type safety and documentation for component usage.

Fix type error in tests

---

src/components/FilterEmptyState/FilterEmptyState.vue

…lues
- Reversed the logic for displaying empty and not found images in the template.
- Updated default values for isEmpty and image props to enhance clarity and usability.
- Improved type safety by using constants for image paths.

Add emptyState images to bundle insteade of relative path
